name: test
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - numpy ==1.20.0
  - jsonschema ==4.0.1
  - pandas ==1.2.0
  - mir_eval ==0.8.2
  - matplotlib-base ==3.3.0
  - sortedcontainers ==2.0.0
  - six
  - decorator
  - pytest
  - coverage
  - pytest-cov
  - pytest-mpl
