[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
addopts = [
    "-v",
    "--cov-report=xml",
    "--cov=jams",
]

testpaths = [
    "tests"
]
