name: CI Testing

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: True

jobs:
  test:
    name: "Python ${{ matrix.python-version }} on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        channel-priority: [strict]
        envfile: [".github/environment-ci.yml"]
        python-version:
        - "3.9"
        - "3.10"
        - "3.11"
        - "3.12"
        - "3.13"
        include:
          - python-version: "3.13"
            os: macos-latest
          - python-version: "3.13"
            os: windows-latest
          - os: ubuntu-latest
            python-version: "3.9"
            envfile: ".github/environment-minimal.yml"
            channel-priority: "flexible"
            name: "Minimal dependencies"

    steps:
    - uses: actions/checkout@v4
    - name: Create conda environment
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: ${{ matrix.python-version }}
        auto-activate-base: false
        channel-priority: ${{ matrix.channel-priority }}
        environment-file: ${{ matrix.envfile }}
        # Disabling bz2 to get more recent dependencies.
        # NOTE: this breaks cache support, so CI will be slower.
        use-only-tar-bz2: False # IMPORTANT: This needs to be set for caching to work properly!
    - name: Install jams
      shell: bash -l {0}
      run: python -m pip install --upgrade-strategy=only-if-needed -e .[display,tests]
    - name: Log installed packages for debugging
      shell: bash -l {0}
      run: |
        python -c "import sys; print(sys.version)"
        conda info -a
        conda list

    - name: Run tests
      shell: bash -l {0}
      run: |
        pytest -v --cov-report term-missing --cov jams

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.xml
        flags: unittests
        env_vars: OS,PYTHON
        name: codecov-umbrella
        fail_ci_if_error: true
        verbose: true
